export type Country = {
  iso: string;
  name: string;
  dial: string;
  flag: string;
};

export const COUNTRIES: Country[] = [
  { iso: "US", name: "États-Unis", dial: "1", flag: "🇺🇸" },
  { iso: "CA", name: "Canada", dial: "1", flag: "🇨🇦" },
  { iso: "GB", name: "Royaume-Uni", dial: "44", flag: "🇬🇧" },
  { iso: "HT", name: "Haïti", dial: "509", flag: "🇭🇹" },
  { iso: "DO", name: "République dominicaine", dial: "1", flag: "🇩🇴" },
  { iso: "MX", name: "Mexique", dial: "52", flag: "🇲🇽" },
  { iso: "FR", name: "France", dial: "33", flag: "🇫🇷" },
  { iso: "BR", name: "Brésil", dial: "55", flag: "🇧🇷" },
  { iso: "CO", name: "Colombie", dial: "57", flag: "🇨🇴" },
  { iso: "AR", name: "Argentine", dial: "54", flag: "🇦🇷" },
  { iso: "CL", name: "Chili", dial: "56", flag: "🇨🇱" },
  { iso: "PE", name: "Pérou", dial: "51", flag: "🇵🇪" },
  { iso: "VE", name: "Venezuela", dial: "58", flag: "🇻🇪" },
  { iso: "EC", name: "Équateur", dial: "593", flag: "🇪🇨" },
  { iso: "JM", name: "Jamaïque", dial: "1", flag: "🇯🇲" },
  { iso: "TT", name: "Trinité-et-Tobago", dial: "1", flag: "🇹🇹" },
  { iso: "BB", name: "Barbade", dial: "1", flag: "🇧🇧" },
  { iso: "BS", name: "Bahamas", dial: "1", flag: "🇧🇸" },
  { iso: "PR", name: "Porto Rico", dial: "1", flag: "🇵🇷" },
  { iso: "CU", name: "Cuba", dial: "53", flag: "🇨🇺" },
  { iso: "GP", name: "Guadeloupe", dial: "590", flag: "🇬🇵" },
  { iso: "MQ", name: "Martinique", dial: "596", flag: "🇲🇶" },
  { iso: "GF", name: "Guyane", dial: "594", flag: "🇬🇫" },
  { iso: "ES", name: "Espagne", dial: "34", flag: "🇪🇸" },
  { iso: "IT", name: "Italie", dial: "39", flag: "🇮🇹" },
  { iso: "DE", name: "Allemagne", dial: "49", flag: "🇩🇪" },
  { iso: "PT", name: "Portugal", dial: "351", flag: "🇵🇹" },
  { iso: "NL", name: "Pays-Bas", dial: "31", flag: "🇳🇱" },
  { iso: "BE", name: "Belgique", dial: "32", flag: "🇧🇪" },
  { iso: "CH", name: "Suisse", dial: "41", flag: "🇨🇭" },
  { iso: "NG", name: "Nigéria", dial: "234", flag: "🇳🇬" },
  { iso: "GH", name: "Ghana", dial: "233", flag: "🇬🇭" },
  { iso: "KE", name: "Kenya", dial: "254", flag: "🇰🇪" },
  { iso: "ZA", name: "Afrique du Sud", dial: "27", flag: "🇿🇦" },
  { iso: "SN", name: "Sénégal", dial: "221", flag: "🇸🇳" },
  { iso: "CI", name: "Côte d'Ivoire", dial: "225", flag: "🇨🇮" },
  { iso: "CM", name: "Cameroun", dial: "237", flag: "🇨🇲" },
  { iso: "MA", name: "Maroc", dial: "212", flag: "🇲🇦" },
  { iso: "DZ", name: "Algérie", dial: "213", flag: "🇩🇿" },
  { iso: "TN", name: "Tunisie", dial: "216", flag: "🇹🇳" },
  { iso: "EG", name: "Égypte", dial: "20", flag: "🇪🇬" },
  { iso: "IN", name: "Inde", dial: "91", flag: "🇮🇳" },
  { iso: "PK", name: "Pakistan", dial: "92", flag: "🇵🇰" },
  { iso: "BD", name: "Bangladesh", dial: "880", flag: "🇧🇩" },
  { iso: "PH", name: "Philippines", dial: "63", flag: "🇵🇭" },
  { iso: "ID", name: "Indonésie", dial: "62", flag: "🇮🇩" },
  { iso: "TH", name: "Thaïlande", dial: "66", flag: "🇹🇭" },
  { iso: "VN", name: "Viêt Nam", dial: "84", flag: "🇻🇳" },
  { iso: "MY", name: "Malaisie", dial: "60", flag: "🇲🇾" },
  { iso: "SG", name: "Singapour", dial: "65", flag: "🇸🇬" },
  { iso: "AU", name: "Australie", dial: "61", flag: "🇦🇺" },
  { iso: "NZ", name: "Nouvelle-Zélande", dial: "64", flag: "🇳🇿" },
  { iso: "JP", name: "Japon", dial: "81", flag: "🇯🇵" },
  { iso: "KR", name: "Corée du Sud", dial: "82", flag: "🇰🇷" },
  { iso: "CN", name: "Chine", dial: "86", flag: "🇨🇳" },
  { iso: "AE", name: "Émirats arabes unis", dial: "971", flag: "🇦🇪" },
  { iso: "SA", name: "Arabie saoudite", dial: "966", flag: "🇸🇦" },
  { iso: "TR", name: "Turquie", dial: "90", flag: "🇹🇷" },
  { iso: "IL", name: "Israël", dial: "972", flag: "🇮🇱" },
  { iso: "PL", name: "Pologne", dial: "48", flag: "🇵🇱" },
  { iso: "RO", name: "Roumanie", dial: "40", flag: "🇷🇴" },
  { iso: "SE", name: "Suède", dial: "46", flag: "🇸🇪" },
  { iso: "NO", name: "Norvège", dial: "47", flag: "🇳🇴" },
  { iso: "DK", name: "Danemark", dial: "45", flag: "🇩🇰" },
  { iso: "IE", name: "Irlande", dial: "353", flag: "🇮🇪" },
  { iso: "AT", name: "Autriche", dial: "43", flag: "🇦🇹" },
  { iso: "GR", name: "Grèce", dial: "30", flag: "🇬🇷" },
  { iso: "RU", name: "Russie", dial: "7", flag: "🇷🇺" },
  { iso: "UA", name: "Ukraine", dial: "380", flag: "🇺🇦" },
  { iso: "CR", name: "Costa Rica", dial: "506", flag: "🇨🇷" },
  { iso: "PA", name: "Panama", dial: "507", flag: "🇵🇦" },
  { iso: "GT", name: "Guatemala", dial: "502", flag: "🇬🇹" },
  { iso: "HN", name: "Honduras", dial: "504", flag: "🇭🇳" },
  { iso: "SV", name: "Salvador", dial: "503", flag: "🇸🇻" },
  { iso: "NI", name: "Nicaragua", dial: "505", flag: "🇳🇮" },
  { iso: "BO", name: "Bolivie", dial: "591", flag: "🇧🇴" },
  { iso: "PY", name: "Paraguay", dial: "595", flag: "🇵🇾" },
  { iso: "UY", name: "Uruguay", dial: "598", flag: "🇺🇾" },
];

export function getCountry(iso: string) {
  return COUNTRIES.find((c) => c.iso === iso) ?? COUNTRIES[0];
}
